# Generated by Django 3.1.3 on 2021-04-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210424_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
